### ISSUE TITLE
No module named 'ankirspy'

### ISSUE THREAD

**Issue by dsabsay** [ankitects/anki-typecheck#2]
OS: macOS 10.14.4
Python: v3.7.5

I've created a virtual environment and installed the 2.1.20 wheels in this repo into it.

Then I try to import something, and get an exception:
```
Python 3.7.5 (default, Nov  1 2019, 02:16:32) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from anki import hooks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/danielsabsay/git/anki_add_on_example/env/lib/python3.7/site-packages/anki/__init__.py", line 7, in <mo
dule>
    from anki.storage import Collection
  File "/Users/danielsabsay/git/anki_add_on_example/env/lib/python3.7/site-packages/anki/storage.py", line 10, in <mo
dule>
    from anki.collection import _Collection
  File "/Users/danielsabsay/git/anki_add_on_example/env/lib/python3.7/site-packages/anki/collection.py", line 17, in 
<module>
    import anki.latex  # sets up hook
  File "/Users/danielsabsay/git/anki_add_on_example/env/lib/python3.7/site-packages/anki/latex.py", line 16, in <modu
le>
    from anki.template import TemplateRenderContext, TemplateRenderOutput
  File "/Users/danielsabsay/git/anki_add_on_example/env/lib/python3.7/site-packages/anki/template.py", line 40, in <m
odule>
    from anki.rsbackend import TemplateReplacementList
  File "/Users/danielsabsay/git/anki_add_on_example/env/lib/python3.7/site-packages/anki/rsbackend.py", line 8, in <m
odule>
    import ankirspy  # pytype: disable=import-error
ModuleNotFoundError: No module named 'ankirspy'
>>> 
```

Have I forgotten to install something?

**Comment by dae** [comment]
The files are only useful for type checking, they can not be used to run Anki's code. Please see https://addon-docs.ankiweb.net/#/getting-started?id=ide-amp-type-hints

**Comment by dsabsay** [comment]
I'm trying to set up type checking. I'm using Vim with [this plugin](https://github.com/neoclide/coc-python) and was assuming the IntelliSense engine (Jedi) would try to import the code, but upon further inspection it appears that is not the case (for good reason really).

There is probably something else I need to fix in my own setup. So I'll close this. Thanks for your quick response though :)
